apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo-ds
    isDefault: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: 'elasticsearch-ds'
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        tags: [{ key: 'service.name', value: 'serviceName' }]
        filterByTraceID: true
        filterBySpanID: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: elasticsearch-ds
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      index: "rabbitprocessor-*"
      database: "[rabbitprocessor-]*"
      version: "7.0.0+"
      logMessageField: "message"
      logLevelField: "level"
      dataLinks:
        - field: "traceId"
          url: '/explore?left={"datasource":"elasticsearch-ds","queries":[{"refId":"A","query":"traceId:\"$${__value.raw}\"","metrics":[{"id":"1","type":"logs"}],"bucketAggs":[]}],"range":{"from":"now-6h","to":"now"}}&right={"datasource":"tempo-ds","queries":[{"refId":"A","queryType":"traceId","query":"$${__value.raw}"}],"range":{"from":"now-6h","to":"now"}}'
