{
 "title": "Pokemon Core Pipeline",
 "tags": [
  "pokemon",
  "core-pipeline",
  "splitter",
  "hbase-writer",
  "webhook"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Splitter Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"splitter\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HBase Writer Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"hbase-writer\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Webhook Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"webhook\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Core Pipeline Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "100" }, "type": "logs" }
     ],
     "query": "(serviceName:\"splitter\" OR serviceName:\"hbase-writer\" OR serviceName:\"webhook\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Core Pipeline Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "limit": 100,
     "query": "{ resource.service.name =~ \"RabbitProcessor-Pipeline-(splitter|hbase-writer|webhook)\" }",
     "tableType": "traces"
    }
   ]
  }
 ]
}