{
 "title": "RabbitProcessor Overview",
 "panels": [
  {
   "title": "Ingested Pokémon",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "statusType:\"algorithmSuccess\" AND serviceName:\"hbase-writer\"",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Webhook Deliveries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "statusType:\"algorithmSuccess\" AND serviceName:\"webhook\"",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "statusType:\"algorithmError\"",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processing Log Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "*",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}