{
 "title": "Pokemon Surname Pipeline",
 "tags": [
  "pokemon",
  "surname",
  "rabbitprocessor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": "pokemon-surname-generator,surname-api,surname-enrichment,hbase-surname-updater"
   }
  ]
 },
 "panels": [
  {
   "title": "Generated Surnames",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"pokemon-surname-generator\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Translations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"surname-api\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HBase Surname Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "serviceName:\"hbase-surname-updater\" AND statusType:\"processingSuccess\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Surname Pipeline Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(serviceName:\"pokemon-surname-generator\" OR serviceName:\"surname-api\" OR serviceName:\"surname-enrichment\" OR serviceName:\"hbase-surname-updater\") AND statusType:\"processingError\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Processing Duration: $service_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "processingDuration", "id": "1", "type": "avg" }
     ],
     "query": "serviceName:\"$service_name\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs And Trace Links: $service_name",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "serviceName:\"$service_name\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}