input {
  tcp {
    port => 5044
    codec => json_lines {
      target => "payload"
    }
  }
}

filter {
  if [payload][project] {
    mutate {
      add_field => { "[@metadata][index_name]" => "%{[payload][project]}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_name]" => "default" }
    }
  }

  if [payload] {
    ruby {
      code => '
        payload = event.get("payload")
        if payload.is_a?(Hash)
          payload.each do |key, value|
            next if ["@timestamp", "@version"].include?(key)
            event.set(key, value)
          end
        end
      '
    }

    mutate {
      remove_field => ["payload"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => false
    index => "rabbitprocessor-logs-%{[@metadata][index_name]}-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
